Show on ToolTip in display units.
NeVeSpl/RevitDBExplorer pull request #5
Opened 2022-10-10 09:53 UTC by yk35

Show BoundingBoxXYZ,XYZ,UV,Double information on ToolTip in display units.

![image](https://user-images.githubusercontent.com/292759/194840047-00d1a883-be5c-4b50-a60b-e3b532eb69b4.png)

2022-10-13 10:01 UTC, yk35 commented
Sorry. I found bug.
I fixed and pushed.

2022-10-17 08:02 UTC, NeVeSpl requested changes
Thank you for your PR, I like the changes, but a few adjustments in naming and file placement will be needed in order to keep consistency before the merge. Also `FeetToMetersConverter ` will need a new name since it is no longer simply feet to meter converter...

2022-10-17 08:02 UTC, NeVeSpl commented on sources/Domain/DataModel/ValueContainers/Base/IHaveDetailInformation.cs
> +    internal interface IHaveDetailInformation
I love introduction of this interface, but I would prefer to use the name IHaveToolTip, and everywhere replace 'DetailInformation' with 'ToolTip'

2022-10-17 08:02 UTC, NeVeSpl commented on sources/Domain/DataModel/ValueContainers/Base/IHaveDetailInformation.cs
> +        string DetailInformationText { get; }
'Text' postfix is not necessary.

2022-10-17 08:02 UTC, NeVeSpl commented on sources/Domain/DataModel/ValueContainers/Base/ToDisplayUnitHelper.cs
> +namespace RevitDBExplorer.Domain.DataModel.ValueContainers.Base
All extension methods should be placed in `Extensions` folder, and have a namespace and class name, file name consistent with other similar classes.

2022-10-17 08:02 UTC, NeVeSpl commented on sources/Domain/DataModel/ValueContainers/BoundingBoxXYZContainer.cs
> +        /// Retrieve BoundingBoxXYZ in mm
the comment is not necessary, it does not add anything valuable, and also it is lying, it will not always be [mm]

2022-10-18 00:07 UTC, yk35 commented
@NeVeSpl 
Thank you for your review.
I will fix it.

I have one question.
> Also FeetToMetersConverter will need a new name since it is no longer simply feet to meter converter...
Does I rename this class SnoopableMemberToToolTipConverter?

2022-10-18 06:48 UTC, NeVeSpl commented
sure, It fits much better to its new responsibility.

2022-10-18 10:20 UTC, yk35 commented
@NeVeSpl 
I fixed code.
Please review again. 
Best regards.

2022-10-18 17:32 UTC, NeVeSpl approved these changes

2022-10-18 17:34 UTC, merged